<a href="https://colab.research.google.com/github/wlsisl/ESAA_22-2/blob/main/2%EC%B0%A8%EA%B3%BC%EC%A0%9C(1~38p).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##CHAPTER 01 _  파이썬 기반의 머신러닝과 생태계 이해
####01.머신러닝의 개념


* 머신러닝(Machine Learning)

애플리케이션을 수정하지 않고도 데이터를 기반으로 패턴을 학습하고 결과를 예측하는 알고리즘 기법을 통칭한다.

ex) 금융 사기 거래 적발 프로그램

문제점: 프로그램 로직을 통해 모든 조건과 다양한 환경 변수, 규칙을 반영하여 사기 거래 적발의 정확성을 높여야하는데, 코드가 복잡할 수록 정확성이 떨어진다. 
업무적으로 복잡한 조건과 규칙들이 다양한 형태로 결합하고 시시각각 변하면서 소프트웨어 코드 로직을 관통하는 패턴을 찾기 어려움

해결방안: 데이터를 기반으로 숨겨진 패턴을 인지해 해결한다. 머신러닝 알고리즘은 통계적 신뢰도를 강화하고 예측 오류를 최소화하기 위한 다양한 수학적 기법으로 패턴을 스스로 인지하고 신뢰도 있는 예측 결과를 도출함. 


* 머신러닝의 분류

1. 지도학습
 분류, 회귀, 추천 시스템, 시각/음성 감지/ 인지, 텍스트 분석, NLP

2. 비지도학습
 클러스터링, 차원 축소, 강화학습


* 데이터 전쟁 
최적의 머신러닝 알고리즘 , 모델 파라미터를 구축하는 능력뿐만 아니라
데이터를 이해하고 효율적으로 가공, 처리, 추출해 최적의 데이터를 기반으로 알고리즘을 구동할 수 있도록 준비하는 능력이 중요하다.

* 파이썬과 R기반의 머신러닝 비교

1. R
통계 전용 프로그램 언어. 

2. Python
다양한 영역에서 사용되는 개발 전문 프로그램 언어.
직관적인 문법, 객체지향과 함수형 프로그래밍
아키텍처, 다양한 라이브러리

####02.파이썬 머신러닝 생태계를 구성하는 주요 패키지

* 머신러닝 패키지 - 사이킷런(Scikit-Learn)
* 행렬/ 선형대수/ 통계 패키지 - 넘파이(Numpy), 사이파이(SciPy)
* 데이터 핸들링 - 판다스
* 시각화 - 맷플롯립(Matplotlib), 사본(Seaborn)

####03. 넘파이


In [2]:
import numpy as np
# as np를 약어로 모듈 표현함
# numpy 기반 데이터 타입은 ndarray. 다차원 배열을 쉽게 생성하고 연산 수행가능

array()함수: 다양한 인자를 입력 받아서 ndarray로 변환하는 기능을 수행함.


In [ ]:
array1=np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)
#1차원 array로 3개의 데이터를 가지고 있음을 뜻한다.

array2 = np.array([[1,2,3],[2,3,4]])
print('array2 type:', type(array2))
print('array2 array형태:', array2.shape)
#2차원 array로 2개의 로우와 3개의 칼럼으로 구성되어 6개의 데이터를 가지고 있음을 뜻한다.

array3= np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array형태:', array3.shape)
# 1개의 로우와 3개의 칼럼으로 구성된 2차원 데이터다.

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array형태: (1, 3)


In [ ]:
print('array1:{:0}차원, array2: {:1}차원, array3: {:2}차원 '.format(array1.ndim,array2.ndim,array3.ndim))

array1:1차원, array2: 2차원, array3:  2차원 


ndarray의 데이터 타입
* 같은 데이터 타입만 가능하다. 한 개의 ndarray객체에 int와 float가 함께 있을 수 없다. 

In [ ]:
list1=[1,2,3]
print(type(list1))
array1=np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [ ]:
#다른 데이터 타입이 함께 쓰인다면?
list2 = [1,2,'test']
array2=np.array(list2)
print(array2, array2.dtype)

list3=[1,2,3.0]
array3=np.array(list3)
print(array3, array3.dtype)

# int형 <float형  < 문자형

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [ ]:
array_int=np.array([1,2,3])
array_float=array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1=array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1=np.array([1.1,2.1,3.1])
array_int2=array_float1.astype('int32')
print(array_int2, array_int2.dtype)


[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


ndarray를 편리하게 생성하기 - arange, zeros, ones
- 테스트용으로 데이터를 만들거나 대규모의 데이터를 일괄적으로 초기화해야 할 경우에 사용

* zeros() 튜플 형태의 shape 값을 입력하면 모든 값을 0으로 채운 해당 shape를 가진 ndarray를 반환한다. 

* ones() 튜플 형태의 shape 값을 입력하면 모든 값을 1로 채운 해당 shape를 가진 ndarray를 반환한다.

dtype를 정해주지 않으면 default로 float64형의 데이터로 ndarray를 채운다.

In [ ]:
sequence_array=np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [ ]:
zero_array=np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array=np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


ndarray의 차원과 크기를 변경하는 reshape()

In [ ]:
array1=np.arange(10)
print('array1:\n',array1)

array2=array1.reshape(2,5)
print('array2:\n',array2)

array3=array1.reshape(5,2)
print('array3:\n',array3)


array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
array1.reshape(4,3)
#지정된 사이즈로 변경이 불가능하면 오류를 발생한다.

ValueError: ignored

In [ ]:
array1=np.arange(10) #1차원
print(array1)

array2=array1.reshape(-1,5) # array1과 호환될 수 있는 2차원 ndarray로 변환하되,
# 고정된 5개 칼럼에 맞는 로우 개수는 2이므로 2x5의 2차원으로 변환함.
print('array2 shape:',array2.shape)

array3=array1.reshape(5,-1)
print('array3 shape:',array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [ ]:
array1=np.arange(10)
array4=array1.reshape(-1,4)

ValueError: ignored

In [ ]:
# <reshape(-1,1)로 차원 변경하기>

array1=np.arange(8)
array3d=array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist())

#3차원 ndarray를 2차원 ndarray로 변환
array5=array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape:', array5.shape)

#1차원 ndarray를 2차원 ndarray로 변환
array6=array1.reshape(-1,1)
print('array6:\n',array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(indexing)
1. 특정한 데이터만 추출
2. 슬라이싱
3. 팬시 인덱싱
4. 불린 인덱싱

In [ ]:
# 단일 값 추출

#1부터 9까지의 1차원 ndarray생성

array1=np.arange(start=1, stop=10)
print('array1:',array1)

#index는 0부터 시작하므로 array1[2]는 3번재 index위치의 데이터값을 의미
value=array1[2]
print('value:',value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


In [ ]:
print('맨 뒤의 값:',array1[-1], '맨 뒤에서 두번째값:', array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두번째값: 8


In [ ]:
array1[0]=9
array1[8]=0
print('array1:',array1)

array1: [9 2 3 4 5 6 7 8 0]


In [ ]:
array1d=np.arange(start=1,stop=10)
array2d=array1d.reshape(3,3)
print(array2d)

print('(row=0,col=0) index가리키는 값:',array2d[0,0])
print('(row=0,col=1) index가리키는 값:',array2d[0,1])
print('(row=1,col=0) index가리키는 값:',array2d[1,0])
print('(row=2,col=2) index가리키는 값:',array2d[2,2])

#넘파이에서는 row 가 아니라 axis0으로 나타냄 , axis1은 col임

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index가리키는 값: 1
(row=0,col=1) index가리키는 값: 2
(row=1,col=0) index가리키는 값: 4
(row=2,col=2) index가리키는 값: 9


슬라이싱
1. [:3] 맨 처음부터 index3까지
2. [3:] index3부터 맨 마지막 인덱스까지

In [ ]:
array1=np.arange(start=1, stop=10)
array3=array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
array1d=np.arange(start=1, stop=10)
array2d=array1d.reshape(3,3)
print('array2d:\n',array2)

print('array2d[0:2,0:2]\n', array2d[0:2, 0:2])
print('array2d[1:3,0:3]\n', array2d[1:3,0:3])
print('array2d[1:3,:]\n', array2d[1:3,:])
print('array2d[:,:]\n', array2d[:,:])
print('array2d[:2,1:]\n', array2d[:2,1:])
print('array2d[:2,0]\n', array2d[:2,0])

array2d:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array2d[0:2,0:2]
 [[1 2]
 [4 5]]
array2d[1:3,0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3,:]
 [[4 5 6]
 [7 8 9]]
array2d[:,:]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2,1:]
 [[2 3]
 [5 6]]
array2d[:2,0]
 [1 4]


In [ ]:
#2차원 ndarray에서 뒤에오는 인덱스를 없애면 1차원을 반환함. 
# ???low만 되는 것일까?

print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1].shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1].shape: (3,)


팬시 인덱싱

In [4]:
array1d= np.arange(start=1, stop=10)
array2d=array1d.reshape(3,3)

array3=array2d[[0,1],2]
print('array2d[[0,1],2]=>', array3.tolist())

array4=array2d[[0,1],0:2]
print('array2d[[0,1],0:2]=>', array4.tolist())

array5=array2d[[0,1]]
print('array2d[[0,1]]=>', array5.tolist())

array2d[[0,1],2]=> [3, 6]
array2d[[0,1],0:2]=> [[1, 2], [4, 5]]
array2d[[0,1]]=> [[1, 2, 3], [4, 5, 6]]


불린 인덱싱

In [5]:
array1d = np.arange(start=1, stop=10)
#[] 안에 array1d > 5 Boolean indexing을 적용

array3=array1d[array1d>5]
print('array1d > 5 불린 인덱싱 결과 값:', array3)


array1d > 5 불린 인덱싱 결과 값: [6 7 8 9]


In [6]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [7]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3=array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과:', array3)

불린 인덱스로 필터링 결과: [6 7 8 9]


In [8]:
indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과:',array4)

일반 인덱스로 필터링 결과: [6 7 8 9]


행렬의 정렬 - sort()와 argsort()


> 

1. 넘파이에서 행렬을 정렬하는 대표적인 방법: np.sort() , ndarray.sort() 

> 

2. 행렬의 인덱스를 반환하는 argsort()

In [10]:
org_array = np.array([3,1,9,5])
print('원본 행렬:', org_array)
# np.sort()로 정렬
sort_array1=np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:',sort_array1)
print('np.sort() 호출 후 원본 행렬:',org_array)
#ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:',sort_array2)
print('org_array.sort() 호출 후 원본 행렬:',org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


In [11]:
sort_array1_desc=np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [12]:
#행렬이 2차원 이상일 경우에
array2d = np.array([[8,12],[7,1]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬 : \n',sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬 : \n',sort_array2d_axis1)

로우 방향으로 정렬 : 
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬 : 
 [[ 8 12]
 [ 1  7]]


정렬된 행렬의 인덱스를 반환하기

np.argsort() 정렬 행렬의 원본 행렬 인덱스를 ndarray형으로 반환

1. 오름차순으로 정렬하고 인덱스 반환하는 것

In [13]:
org_array=np.array([3,1,9,5])
sort_indices=np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:',sort_indices)


<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


2. 내림차순으로 정렬하고 인덱스 반환하는 것

In [14]:
org_array=np.array([3,1,9,5])
sort_indices_desc=np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:',sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [15]:
import numpy as np

name_array=np.array(['John', 'Mike','Sarah',"Kate",'Samuel'])
score_array=np.array([78,95,84,98,88])

sort_indices_asc= np.argsort(score_array)
print('성적 오름차순 정렬시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])


성적 오름차순 정렬시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


선형대수 연산 - 행렬 내적과 전치 행렬 구하기

1. 행렬 내적(행렬 곱)

np.dot()을 이용해 계산

In [18]:
A=np.array([[1,2,3],[4,5,6]])
B=np.array([[7,8],[9,10],[11,12]])
dot_product=np.dot(A,B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


2. 전치 행렬

transpose()를 이용

In [19]:
A=np.array([[1,2],[3,4]])
transpose_mat=np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
